apiVersion: v1 
 
kind: Pod 
 
metadata: 
  name: webserver 
 
spec: 
  containers: 
  - name: webserver 
    image: nginxinc/nginx-unprivileged:1.22.0 
    ports: 
    - containerPort: 8080 
      protocol: TCP 
    securityContext: 
      readOnlyRootFilesystem: true 
      runAsNonRoot: true 
    resources: 
      limits: 
        cpu: "200m" 
        memory: "20Mi" 
      requests: 
        cpu: "100m" 
        memory: "10Mi" 
    volumeMounts: 
    - mountPath: /tmp 
      name: tmp 
 
  volumes: 
  - emptyDir: {} 
    name: tmp
